# Generated by Django 3.2 on 2022-02-23 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(related_name='product_disliked', to='accounts.UserProfile')),
                ('likes', models.ManyToManyField(related_name='product_loved', to='accounts.UserProfile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
