# Generated by Django 3.2 on 2022-02-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220121_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('unlike', 'unlike')], max_length=100),
        ),
    ]
